---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: docker
    run_list: recipe[kubernetes::docker]
    attributes:

  - name: etcd_test
    run_list:
    - recipe[etcd_test::installation_binary, etcd_test::service_execute, etcd_test::service_systemd, etcd_test::keys, etcd_test::auto]