---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: docker
    run_list: recipe[kubernetes::docker]
    attributes:

  - name: etcd_installation_binary_test
    run_list:
    - recipe[etcd_test::installation_binary]

  - name: etcd_service_execute_test
    run_list:
    - recipe[etcd_test::service_execute]

  - name: etcd_service_systemd_test
    run_list:
    - recipe[etcd_test::service_systemd]

  - name: etcd_keys_test
    run_list:
    - recipe[etcd_test::keys]

  - name: etcd_auto_test
    run_list:
    - recipe[etcd_test::auto]