---
driver:
  name: vagrant
  network:
    -
      - private_network
      - type: dhcp
  customize:
    memory: 756

provisioner:
  name: nodes

platforms:
  - name: centos-7.2

verifier:
  name: inspec
  sudo: true

suites:
  - name: master1
    run_list:
      - recipe[vagrant]
      - recipe[kubernetes::client_wrapper]
      - recipe[kubernetes::consul]
      - recipe[kubernetes::vault]
      - recipe[kubernetes::vault-init]
      - recipe[kubernetes::etcd]
      - recipe[kubernetes::docker]
      - recipe[kubernetes::calico]
      - recipe[kubernetes::kubeproxy]
      - recipe[kubernetes::master]
      - recipe[kubernetes::slave]
      - recipe[kubernetes::addons]
    attributes:
      tags:
        - etcd
        - master

  - name: master2
    run_list:
      - recipe[vagrant]
      - recipe[kubernetes::client_wrapper]
      - recipe[kubernetes::etcd]
      - recipe[kubernetes::docker]
      - recipe[kubernetes::calico]
      - recipe[kubernetes::kubeproxy]
      - recipe[kubernetes::master]
      - recipe[kubernetes::slave]
    attributes:
      tags:
        - etcd
        - master

  - name: master3
    run_list:
      - recipe[vagrant]
      - recipe[kubernetes::client_wrapper]
      - recipe[kubernetes::etcd]
      - recipe[kubernetes::docker]
      - recipe[kubernetes::calico]
      - recipe[kubernetes::kubeproxy]
      - recipe[kubernetes::master]
      - recipe[kubernetes::slave]
    attributes:
      tags:
        - etcd
        - master

  - name: slave1
    run_list:
      - recipe[vagrant]
      - recipe[kubernetes::client_wrapper]
      - recipe[kubernetes::docker]
      - recipe[kubernetes::calico]
      - recipe[kubernetes::kubeproxy]
      - recipe[kubernetes::slave]
    attributes:
      tags:
        - slave

  - name: slave2
    run_list:
      - recipe[vagrant]
      - recipe[kubernetes::client_wrapper]
      - recipe[kubernetes::docker]
      - recipe[kubernetes::calico]
      - recipe[kubernetes::kubeproxy]
      - recipe[kubernetes::slave]
    attributes:
      tags:
        - slave
