---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: docker
    run_list: recipe[kubernetes::docker]
    attributes:
    
  - name: etcd_test_binary_installation
    run_list:
    - recipe[etcd_test::installation_binary]

  - name: etcd_test_service-execute
    run_list:
      - recipe[etcd_test::service_execute]

  - name: etcd_test_service-systemd
    includes: [
      'centos-7.2'
    ]
    run_list:
      - recipe[etcd_test::service_systemd]

  - name: etcd_test_keys
    includes: [
      'centos-7'
    ]
    run_list:
      - recipe[etcd_test::keys]

  - name: etcd_test_with_etcdctl
    run_list:
      - recipe[etcd_test::auto]