---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

verifier:
  name: inspec
  sudo: true

suites:
  - name: docker
    run_list:
      - recipe[kubernetes::docker]
    attributes:

  - name: etcd
    run_list:
      - recipe[kubernetes::etcd]
