---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: docker
    run_list: recipe[kubernetes::docker]
    attributes:

  - name: etcd
    run_list:
    - recipe[kubernetes::etcd]